title: All Day DevOps Community 
email: webmin@addo.community
description: >- # this means to ignore newlines until "baseurl:"
  Community presence for the awesome All Day DevOps virtual conference
  Look here for more content, meetups and ways to share 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

